### PR TITLE
Added Mic

### PR DESCRIPTION
**Pull request by hammyexe**

### CODE REVIEW

**Review by qwsdcvghyu89 — CHANGES_REQUESTED** [review]
The URL.createObjectURL method creates a temporary-local only URL. Please modify this code so it stores the recorded audio permanently under a specific folder.

**Comment by hammyexe** [comment]
Changed

**Comment by qwsdcvghyu89** [comment]
Definitely a step in the right direction, but it would be better if there were methods to start and stop recording, rather than time-based controls. Potentially, this could be a class.

**Comment by hammyexe** [comment]
Added Functions

**Comment by qwsdcvghyu89** [comment]
Looks good to me. Well done!

**Pull request merged**
